In [1]:
import numpy as np
import homeless_service as hs

In [2]:
prob = hs.problem_generator('input2.txt')

In [3]:
arrays1 = [np.random.rand(1,7) for i in range(100)]
arrays2 = [np.random.rand(1,7) for i in range(100)]

In [4]:
%time reduce(np.add,arrays1) > 52

CPU times: user 157 µs, sys: 36 µs, total: 193 µs
Wall time: 196 µs


array([[ True, False, False, False, False, False, False]])

In [5]:
%time np.add.reduce(arrays2) >52

CPU times: user 996 µs, sys: 915 µs, total: 1.91 ms
Wall time: 1.12 ms


array([[False, False,  True, False, False,  True,  True]])

In [6]:
%timeit reduce(np.add,arrays1) > 52

10000 loops, best of 3: 42.2 µs per loop


In [7]:
%timeit np.add.reduce(arrays2) >52

The slowest run took 10.11 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 40.5 µs per loop


In [8]:
res = np.add.reduce(arrays2) >52

In [9]:
res

array([[False, False,  True, False, False,  True,  True]])

In [10]:
np.all(res)

False

In [11]:
np.all([True,True])

True