In [1]:
import numpy as np
b = bin(10)
bin(10).count('1')

2

In [2]:
type(b),b,int(b[2:],2)

(str, '0b1010', 10)

In [3]:
a = 0b1010;c = 0b1011
bin(a & c)

'0b1010'

In [4]:
res = np.uint16('1010')
res,type(res)

(1010, numpy.uint16)

In [5]:
N = 15
#[['0'*N for n in range(N)] for i in range(5)]
import sys
sizeof = sys.getsizeof
import numpy as np

In [6]:
list_int_map = [[2**N for n in range(N)] for i in range(12)]
np_int16_map = [np.zeros(shape=(N,1),dtype=np.int16) for i in range(12)]
sizeof(list_int_map), sizeof(np_int16_map)

(200, 200)

In [7]:
N = 20
list_int20_map = [[0 for n in range(10)] for i in range(12)]
np_int16_map = [np.ones(shape=(10,1),dtype=np.uint16) for i in range(12)]
sizeof(list_int20_map), sizeof(np_int16_map)

(200, 200)

In [8]:
num8 = np.array(2**8,dtype=np.uint8);num16 = np.array(2**16,dtype=np.uint16)
num32 = np.array(2**31,dtype=np.uint32);num64 = np.array(2**50,dtype=np.uint64)
sizeof(num8), sizeof(num16), sizeof(num32), sizeof(num64)

(81, 82, 84, 88)

In [9]:
l1 = [[i,i+1,i+2,i+4,i+5,i+6,i+7] for i in range(30)]
l2 = np.array([[i,i+1,i+2,i+4,i+5,i+6,i+7] for i in range(30)])
sizeof(l1), sizeof(l2)

(352, 1792)

In [10]:
N=4
sizeof([[1 for n in range(N)] for i in range(12)]),sizeof(np.array([[0 for n in range(N)] for i in range(12)])) 

(200, 496)

In [11]:
sizeof([[2 for n in range(N)] for i in range(12)]),sizeof(np.array([[3 for n in range(N)] for i in range(12)])) 

(200, 496)

In [12]:
N = 40
string1 = [[[True,False]*8 for i in range(N)] for t in range(12)]
#[[True, False, False, False, True, True, True],[False, False, True, False, False, True, True]]
string2 = [[['10'*8] for i in range(N)] for t in range(12)]
#[['1000111'],['0010011']]
sizeof(string1), sizeof(string2)

(200, 200)

In [13]:
sizeof(False),sizeof('0')

(24, 38)

In [14]:
import pilot_scooter as ps

SyntaxError: invalid syntax (pilot_scooter.py, line 25)

In [ ]:
in_path = ['input1.txt','input2.txt','input3.txt']
case = [ps.problem_generator(path) for path in in_path]
for i in range(3):
    case[i].omap = ps.OLocationMap(N=case[i].N,mat_map=case[i].smap.mat_map[0])
# points1 = [ps.point_calculator(case[i].smap, case[i].omap) for i in range(3)]

In [ ]:
from itertools import combinations
l = [0,1,2,3,4,5]
all_row_comb = list(combinations(range(5),3))

In [ ]:
from itertools import permutations
def check_conflict_set(N,P):
    res = []
    for row in combinations(range(N),P):
        for col in permutations(range(N),P):
            abs_minus = np.abs(np.array(col) - np.array(row))
            if len(abs_minus)==len(set(abs_minus)):
                res.append([row,col])
    return res
               
# all_col_perm

In [ ]:
N = 9
P = 9
print "Using set:"
%time res = check_conflict_set(N,P)

In [ ]:
# def comrow(N,P):
#     j = 0
#     i = 0
#     for pair in combinations(range(N),P):
#         i += 1
#         for col in permutations(range(N),P):
#             j += 1

In [ ]:
N = 13
P = 9
# print "using permutation:"
# %time res = permutations(range(N),P)
# print "using combinations:"
# %time res = combinations(range(N),P)
# %time comrow(N,P)

In [ ]:
def test_main(in_path):
    ps_problem = ps.problem_generator(in_path)
    print("N = %d, P = %d, S = %d:" % (ps_problem.N, ps_problem.P, ps_problem.S))
    result = ps_problem.solve_stupid()
    ps_problem.output_result('output.txt')

In [ ]:
%time test_main('input3.txt')

In [ ]:
%time test_main('input2.txt')

In [ ]:
%time test_main('input1.txt')

In [ ]:
import filecmp

In [ ]:
filecmp.cmp('../HW1b/solution3.txt', '../HW1b/output3.txt')

In [ ]:
from itertools import combinations
list(combinations(range(4),4))

In [ ]:
def using_stupid(in_path):
    ps_problem = ps.problem_generator(in_path)
    result = ps_problem.solve_stupid()
    print "best: "+ str(result['point'])

def using_smart(in_path):
    ps_problem = ps.problem_generator(in_path)
    result = ps_problem.solve_smart()
    print "best: "+ str(result['point'])

In [ ]:
# in_path = 'input1.txt'
# print "="*8 + in_path + "="*8
# print "Using smart:"
# %time using_smart(in_path)
# print "Using stupid:"
# %time using_stupid(in_path)

# in_path = 'input2.txt'
# print "="*8 + in_path + "="*8
# print "Using smart:"
# %time using_smart(in_path)
# print "Using stupid:"
# %time using_stupid(in_path)

# in_path = 'input3.txt'
# print "="*8 + in_path + "="*8
# print "Using smart:"
# %time using_smart(in_path)
# print "Using stupid:"
# %time using_stupid(in_path)

# in_path = 'input4.txt'
# print "="*8 + in_path + "="*8
# print "Using smart:"
# %time using_smart(in_path)
# # print "Using stupid:"
# # %time using_stupid(in_path)

In [15]:
import numpy as np
matrices= [np.random.rand(9,9) for i in range(12)]

In [16]:
sum1 = reduce(np.add, matrices)
sum2 = matrices[0]
for i in range(11):
    sum2 = np.add(sum2,matrices[i+1])

In [17]:
sum2 == sum1

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [3]:
import numpy as np
smat = np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13],[13,14,15,16,17],[17,18,19,20,21]])
smat

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13],
       [13, 14, 15, 16, 17],
       [17, 18, 19, 20, 21]])

In [9]:
row = [0,1,2,4]
P_tmp = 1
smat[row[P_tmp+1:],:]

array([[ 9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21]])

In [10]:
np.max(smat[row[P_tmp+1:],:],axis=1)

array([13, 21])

In [1]:
f = 0.527
s = 680
s/f

1290.3225806451612

In [5]:
import math
math.factorial(15)

1307674368000